name: Web App Demo CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Unit Tests
        run: pytest -v
      - name: Run Security Scan
        run: bandit -r
        continue-on-error: true

  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-test-scan
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gp1-demo:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gp1-demo:latest
